# Generated by Django 5.0.7 on 2024-07-17 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcha', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(blank=True, db_table='users_like', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='group',
            table='groups',
        ),
        migrations.AlterModelTable(
            name='image',
            table='images',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
